- .pre-commit-config.yaml
> Clean up the pre-commit config and root folder

- .dockerignore
> Add basic `.dockerignore`

- .github/workflows/first_interaction.yml
Add action for first interaction,
The action will automatically welcome new contributors when they open their first issue or pull request.
> Add action First Interaction

- .pre-commit-config.yaml
- b.sh
> Indent shell scripts with tabs; fix pre-commit

- example/bintext.py
- src/encoding.py
- src/hex.py
- test/tests.py
> Format Python files with black

- .github/workflows/build-release.yml
> gha: fix create-release job

- .pre-commit-config.yaml
> Add `gitleaks` to `pre-commit`

- README.md
Just added a link to the `programming language` to wikipedia
> [DOCS], added a link to the README file

- .pre-commit-config.yaml
Also ran `pre-commit autoupdate` to update the hooks.
https://pre-commit.com/#pre-commit-autoupdate
> Update the pre-commit config

- .prettierignore
- test/layout/body-hover/index.html
- test/layout/body-hover/style.css
- test/layout/custom-font/index.html
- test/layout/custom-font/style.css
> `prettier` ignore the `test` directory

- .pre-commit-config.yaml
- pyproject.toml
> Add `bandit` to `pre-commit`

- .pre-commit-config.yaml
> Add more details to the pre-commit config

- .pre-commit-config.yaml
- pyproject.toml
> Add Python vulture to pre-commit

- build-webassembly.sh
Run:
`shfmt -l -w .`
https://github.com/mvdan/sh
> Fix Super-Linter SHELL_SHFMT errors

- .prettierignore
- README.md
> Fix markdownlint

- config/admin/app.py
- config/module/utils.py
- config/sync.py
> Run `ruff check --fix`

- test/tests.py
> Ruff fixup

- .github/linters/codespell.txt
- src/test.js
Please include a brief description of the changes introduced by this pull request.
If this pull request addresses or resolves an existing issue, please reference it here.
Outline the changes made in this pull request and explain their purpose.
Add any additional notes or context about this pull request.
> Fix codespell pre-commit

- README.md
> Update README.md copyright years

- config/yaml/layout/type.yaml
> Fix YAML indentS

- build/attribute.py
- build/tags/a.py
- build/tags/area.py
- build/tags/dialog.py
- build/tags/fieldset.py
- build/tags/figcaption.py
- build/tags/figure.py
- build/tags/footer.py
- build/tags/form.py
- build/tags/h1.py
- build/tags/h2.py
- build/tags/h3.py
- build/tags/h4.py
- build/tags/h5.py
- build/tags/h6.py
- build/tags/header.py
- build/tags/hgroup.py
- build/tags/hr.py
- build/tags/i.py
- build/tags/iframe.py
- build/tags/img.py
- build/tags/input.py
- build/tags/td.py
- build/tags/textarea.py
- build/tags/th.py
- build/tags/video.py
- build/type.py
- build/value.py
- config/admin/templates/edit.html.jinja
> trim trailing whitespace

- build/tags/run_all.sh
> Run shell format; shfmt -w -l

- .pre-commit-config.yaml
- .prettierignore
Please include a brief description of the changes introduced by this pull request.
If this pull request addresses or resolves an existing issue, please reference it here.
Outline the changes made in this pull request and explain their purpose.
Add any additional notes or context about this pull request.
> pre-commit autoupdate

- b.sh
- build_and_run.sh
> Format shell scripts with tabs

- .github/workflows/build-release.yml
- .github/workflows/first-interaction.yml
- .github/workflows/make-run.yml
- .github/workflows/pr-labeler.yml
- .github/workflows/pre-commit.yml
- .github/workflows/proselint.yml
- .github/workflows/run-sync-script.yaml
- .github/workflows/super-linter.yml
- .github/workflows/test-git-clone.yml
- .github/workflows/web-assembly.yml
- 🚀 Build and Release Salam
- 👋 First Interaction
- 🧪 Test make run
- 🏷️ Pull Request Labeler
- ✅ Test (pre-commit)
- 📝 Proselint Check
- 🔄 Run Sync Script
- 🔍 Super-Linter
- 🔧 Basic checks
- 🌐 Build and Deploy WebAssembly
Added meaningful emojis to improve workflow visibility and user experience in GitHub Actions.
Please include a brief description of the changes introduced by this pull request.
If this pull request addresses or resolves an existing issue, please reference it here.
Outline the changes made in this pull request and explain their purpose.
Add any additional notes or context about this pull request.
> ✨ Add emojis to all workflow name keys (fixes #1086)

- b.py
> Update b.py - Fix mypy errors

- .github/workflows/pre-commit.yml
fixing Super-Linter errors in YAML prettier
Fixes: #1103
> Fix: Correct YAML formatting
